services:
  explorer:
    image:
      tag: sha-3883f979
    replicaCount: 1
    resources:
      limits:
        cpu: 4
        memory: 14Gi
      requests:
        cpu: 2
        memory: 4Gi
    env:
      - name: AWS_REGION
        value: us-west-2
      - name: AWS_DEFAULT_REGION
        value: us-west-2
      - name: REMOTE_DEV_PREFIX
        value: /$(__ARGUS_STACK_NAME)
      - name: DATA_LOCATOR_DOMAIN
        value: api.$(__ARGUS_STACK_INGRESS_HOST)
      - name: API_DOMAIN
        value: api.$(__ARGUS_STACK_INGRESS_HOST)
      - name: WEB_DOMAIN
        value: $(__ARGUS_STACK_INGRESS_HOST)
      - name: DEPLOYMENT_STAGE
        value: staging
      - name: CXG_BUCKET_PATH
        value: hosted-cellxgene-staging
