services:
  explorer:
    serviceAccount:
      annotations:
        "eks.amazonaws.com/role-arn": arn:aws:iam::699936264352:role/data_portal_staging_explorer
    image:
      tag: sha-3883f979
    replicaCount: 1
    resources:
      limits:
        cpu: 4
        memory: 14Gi
      requests:
        cpu: 2
        memory: 4Gi
    env:
      # env vars common to all deployment stages
      - name: AWS_REGION
        value: us-west-2
      - name: AWS_DEFAULT_REGION
        value: us-west-2
      - name: REMOTE_DEV_PREFIX
        value: /$(__ARGUS_STACK_NAME)
      - name: DATA_LOCATOR_DOMAIN
        value: api.$(__ARGUS_STACK_INGRESS_HOST)
      - name: WEB_DOMAIN
        value: $(__ARGUS_STACK_INGRESS_HOST)

      # env vars specific to this deployment stage
      - name: DEPLOYMENT_STAGE
        value: staging
      - name: API_DOMAIN
        value: api.$(__ARGUS_STACK_INGRESS_HOST)
      - name: CXG_BUCKET_PATH
        value: hosted-cellxgene-staging
