stack:
  services:
    explorer:
      serviceAccount:
        annotations:
          "eks.amazonaws.com/role-arn": arn:aws:iam::699936264352:role/data_portal_staging_explorer
      image:
        tag: sha-40331e28
      replicaCount: 1
      resources:
        limits:
          cpu: 4
          memory: 12Gi
        requests:
          cpu: 2
          memory: 4Gi
      env:
        # env vars common to all deployment stages
        - name: AWS_REGION
          value: us-west-2
        - name: AWS_DEFAULT_REGION
          value: us-west-2
        - name: REMOTE_DEV_PREFIX
          value: /$(__ARGUS_STACK_NAME)
        - name: DEPLOYMENT_STAGE
          value: $(__ARGUS_DEPLOYMENT_STAGE)

        # env vars specific to this deployment stage
        - name: WEB_DOMAIN
          value: cellxgene.staging.single-cell.czi.technology
        - name: API_DOMAIN
          value: api.cellxgene.staging.single-cell.czi.technology
        - name: DATA_LOCATOR_DOMAIN
          value: api.cellxgene.staging.single-cell.czi.technology
        - name: CXG_BUCKET_PATH
          value: hosted-cellxgene-$(__ARGUS_DEPLOYMENT_STAGE)
      ingress:
        rules:
          - host: cellxgene.staging.single-cell.czi.technology
          - host: api.cellxgene.staging.single-cell.czi.technology
