stack:
  global:
    ingress:
      rules:
        - host: platform.staging.virtual-cells.czi.technology
    oidcProxy:
      extraArgs:
        - --cookie-refresh=45m
        - --cookie-expire=24h
        - --cookie-domain=.staging.virtual-cells.czi.technology
        - --whitelist-domain=vcp-staging.auth.us-west-2.amazoncognito.com
        - --auth-logging=false
        - --request-logging=false
  services:
    explorer:
      serviceAccount:
        create: true
        automount: true
        annotations:
          "eks.amazonaws.com/role-arn": arn:aws:iam::058264139299:role/virtual-cells-platform-backend-staging
      image:
        tag: sha-37f8808
      replicaCount: 1
      resources:
        limits:
          cpu: 4
          memory: 12Gi
        requests:
          cpu: 2
          memory: 4Gi
      env:
        # env vars common to all deployment stages
        - name: AWS_REGION
          value: us-west-2
        - name: AWS_DEFAULT_REGION
          value: us-west-2
        - name: REMOTE_DEV_PREFIX
          value: /$(__ARGUS_STACK_NAME)
        - name: DEPLOYMENT_STAGE
          value: $(__ARGUS_DEPLOYMENT_STAGE)
        # env vars specific to this deployment stage
        - name: WEB_DOMAIN
          value: platform.staging.virtual-cells.czi.technology
        - name: API_DOMAIN
          value: $(__ARGUS_STACK_INGRESS_HOST)
        - name: BYOD_WORKFLOWS_BUCKET_PATH
          value: byod-workflows-dev
        - name: DATA_LOCATOR_DOMAIN
          value: $(__ARGUS_STACK_INGRESS_HOST)
        - name: CXG_BUCKET_PATH
          value: hosted-cellxgene-dev
        - name: BYOD_WORKFLOWS_BUCKET_PATH
          value: byod-workflows-dev
