global:
  replicaCount: 1
  autoscaling:
    enabled: true
  service:
    port: 6000
services:
  explorer:
    serviceAccount:
      create: true
      automount: true
      annotations:
        "eks.amazonaws.com/role-arn": arn:aws:iam::699936264352:role/data_portal_dev_explorer
    image:
      repository: 471112759938.dkr.ecr.us-west-2.amazonaws.com/core-platform/single-cell-explorer/explorer
