server:
  app:
    force_https: true
    port: 5005
    debug: false
    verbose: false
    testing: true
    disable_auth: true
    is_vcp_deployment: false

  multi_dataset:
    dataroots:
      test_dataroot:
        base_url: d
        dataroot: "example-dataset/"
    index: true

  gene_info:
    api_base: "https://api.cellxgene.dev.single-cell.czi.technology/gene_info/v1"
default_dataset:
  presentation:
    max_categories: 1000
    custom_colors: true

  embeddings:
    names: []
