# automatically generated by the FlatBuffers compiler, do not modify

# namespace: NetEncoding

import flatbuffers
from flatbuffers.compat import import_numpy

np = import_numpy()


class Int32FBArray(object):
    __slots__ = ["_tab"]

    @classmethod
    def GetRootAs(cls, buf, offset=0):  # type: ignore
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = Int32FBArray()
        x.Init(buf, n + offset)  # type: ignore
        return x

    @classmethod
    def GetRootAsInt32FBArray(cls, buf, offset=0):  # type: ignore
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)  # type: ignore

    # Int32FBArray
    def Init(self, buf, pos):  # type: ignore
        self._tab = flatbuffers.table.Table(buf, pos)

    # Int32FBArray
    def Data(self, j):  # type: ignore
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(
                flatbuffers.number_types.Int32Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 4)
            )
        return 0

    # Int32FBArray
    def DataAsNumpy(self):  # type: ignore
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Int32Flags, o)
        return 0

    # Int32FBArray
    def DataLength(self):  # type: ignore
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # Int32FBArray
    def DataIsNone(self):  # type: ignore
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        return o == 0


def Start(builder):  # type: ignore
    builder.StartObject(1)


def Int32FBArrayStart(builder):  # type: ignore
    """This method is deprecated. Please switch to Start."""
    return Start(builder)  # type: ignore


def AddData(builder, data):  # type: ignore
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(data), 0)


def Int32FBArrayAddData(builder, data):  # type: ignore
    """This method is deprecated. Please switch to AddData."""
    return AddData(builder, data)  # type: ignore


def StartDataVector(builder, numElems):  # type: ignore
    return builder.StartVector(4, numElems, 4)


def Int32FBArrayStartDataVector(builder, numElems):  # type: ignore
    """This method is deprecated. Please switch to Start."""
    return StartDataVector(builder, numElems)  # type: ignore


def End(builder):  # type: ignore
    return builder.EndObject()


def Int32FBArrayEnd(builder):  # type: ignore
    """This method is deprecated. Please switch to End."""
    return End(builder)  # type: ignore
