# automatically generated by the FlatBuffers compiler, do not modify

# namespace: NetEncoding


class TypedFBArray(object):
    NONE = 0
    Float32FBArray = 1
    Int32FBArray = 2
    Uint32FBArray = 3
    Float64FBArray = 4
    JSONEncodedFBArray = 5
    CatInt8FBArray = 6
    CatInt16FBArray = 7
    CatInt32FBArray = 8
    SparseFloat32FBArray = 9
    SparseFloat64FBArray = 10
