# automatically generated by the FlatBuffers compiler, do not modify

# namespace: NetEncoding

class TypedArray(object):
    NONE = 0
    Float32Array = 1
    Int8Array = 2
    Int16Array = 3
    Int32Array = 4
    Uint32Array = 5
    Float64Array = 6
    JSONEncodedArray = 7

