stack:
  global:
    ingress:
      annotations:
        nginx.ingress.kubernetes.io/auth-type: basic
        nginx.ingress.kubernetes.io/auth-secret: basic-auth
        nginx.ingress.kubernetes.io/auth-realm: "Authentication Required - foo"
  services:
    explorer:
      serviceAccount:
        create: true
        automount: true
        annotations:
          "eks.amazonaws.com/role-arn": arn:aws:iam::058264139299:role/virtual-cells-platform-backend-dev
      image:
        tag: sha-ef49424
      replicaCount: 1
      ingress:
        oidcProtected: false
      env:
        # env vars common to all deployment stages
        - name: AWS_REGION
          value: us-west-2
        - name: AWS_DEFAULT_REGION
          value: us-west-2
        - name: REMOTE_DEV_PREFIX
          value: /$(__ARGUS_STACK_NAME)
        - name: DEPLOYMENT_STAGE
          value: $(__ARGUS_DEPLOYMENT_STAGE)
        # env vars specific to this deployment stage
        - name: WEB_DOMAIN
          value: $(__ARGUS_STACK_INGRESS_HOST)
        - name: API_DOMAIN
          value: $(__ARGUS_STACK_INGRESS_HOST)
        - name: DATA_LOCATOR_DOMAIN
          value: $(__ARGUS_STACK_INGRESS_HOST)
        - name: BYOD_WORKFLOWS_BUCKET_PATH
          value: byod-workflows-dev
        - name: CXG_BUCKET_PATH
          value: hosted-cellxgene-dev
        - name: SKIP_ATAC_CACHE
          value: "1"
