stack:
  global:
    oidcProxy:
      extraArgs:
        - --cookie-refresh=45m
        - --cookie-expire=24h
        - --cookie-domain=.dev-vcp.dev.czi.team
        - --whitelist-domain=vcp-staging.auth.us-west-2.amazoncognito.com
        - --auth-logging=false
        - --request-logging=false
  services:
    explorer:
      serviceAccount:
        create: true
        automount: true
        annotations:
          "eks.amazonaws.com/role-arn": arn:aws:iam::058264139299:role/virtual-cells-platform-backend-dev
      image:
        tag: sha-06a389d
      replicaCount: 1
      env:
        # env vars common to all deployment stages
        - name: AWS_REGION
          value: us-west-2
        - name: AWS_DEFAULT_REGION
          value: us-west-2
        - name: REMOTE_DEV_PREFIX
          value: /$(__ARGUS_STACK_NAME)
        - name: DEPLOYMENT_STAGE
          value: $(__ARGUS_DEPLOYMENT_STAGE)
        # env vars specific to this deployment stage
        - name: WEB_DOMAIN
          value: $(__ARGUS_STACK_INGRESS_HOST)
        - name: API_DOMAIN
          value: $(__ARGUS_STACK_INGRESS_HOST)
        - name: DATA_LOCATOR_DOMAIN
          value: $(__ARGUS_STACK_INGRESS_HOST)
        - name: BYOD_WORKFLOWS_BUCKET_PATH
          value: byod-workflows-dev
        - name: SKIP_ATAC_CACHE
          value: "1"
