name: Update prod

on:
  release:
    types: [published]

jobs:
  prod_stack_upsert:
    runs-on: [ARM64, self-hosted, Linux]
    permissions:
        id-token: write
        contents: read

    steps:
      - name: Upsert Prod Stack
        uses: chanzuckerberg/argus-artifacts/ci/packages/create-stack@v0.19.1
        with:
          appName: single-cell-explorer
          envName: prod
