name: Docker Image Build - staging/prod

on:
  - push

jobs:
  argus_builder:
    uses: chanzuckerberg/github-actions/.github/workflows/argus-docker-build.yaml@v6
    secrets: inherit
    with:
      envs: staging,prod
      path_filters: "!**/.infra/**"
      branches_include: release-please--branches--main
      force_update_manifests: true
      images: |
        {
          "explorer": {
            "context": ".",
            "dockerfile": "hosted/Dockerfile",
            "argus_root": ".",
            "platform": "linux/amd64",
            "build_args": [
              "BUILDKIT_INLINE_CACHE=1"
            ]
          },
          "explorer-vcp": {
            "context": ".",
            "dockerfile": "vcp-hosted/Dockerfile",
            "argus_root": "vcp-infra",
            "platform": "linux/amd64",
            "build_args": [
              "BUILDKIT_INLINE_CACHE=1"
            ]
          }
        }
