name: Docker Image Build - rdev

on:
  - push

jobs:
  rdev_argus_builder:
    uses: chanzuckerberg/github-actions/.github/workflows/argus-docker-build.yaml@v2.9.0
    secrets: inherit
    with:
      branches_ignore: main,release-please--branches--main
      path_filters: '!.infra/**,!.github/**,!.happy/**,!dev_docs/**,!example-dataset/**'
      envs: rdev
      images: |
        [
          {
            "name": "explorer",
            "context": ".",
            "dockerfile": "hosted/Dockerfile",
            "platform": "linux/amd64"
          }
        ]
