name: Docker Image Build

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
    workflow_dispatch: {}
    push:
        paths-ignore:
            - '.infra/**'
            - '.github/**'
            - '.happy/**'
            - 'dev_docs/**'
            - 'example-dataset/**'
        branches-ignore:
          - main

jobs:
  argus_builder:
    uses: chanzuckerberg/github-actions/.github/workflows/argus-docker-build.yaml@heathj/configurable-platform
    secrets: inherit
    with:
      env: rdev
      images: |
        [
          {
            "name": "explorer",
            "context": ".",
            "dockerfile": "hosted/Dockerfile",
            "platform": "linux/amd64"
          }
        ]
