name: "Lint argus helm chart - vcp-explorer"

on:
  - pull_request

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  lint-prod:
    runs-on: ubuntu-latest
    steps:
      - uses: chanzuckerberg/github-actions/.github/actions/helm-lint@v6
        with:
          chart_path: vcp-infra/.infra/prod
          values_files: ../common.yaml,./values.yaml
  lint-rdev:
    runs-on: ubuntu-latest
    steps:
      - uses: chanzuckerberg/github-actions/.github/actions/helm-lint@v6
        with:
          chart_path: vcp-infra/.infra/rdev
          values_files: ../common.yaml,./values.yaml
  lint-staging:
    runs-on: ubuntu-latest
    steps:
      - uses: chanzuckerberg/github-actions/.github/actions/helm-lint@v6
        with:
          chart_path: vcp-infra/.infra/staging
          values_files: ../common.yaml,./values.yaml

