name: Push Remote Dev

on:
  push:
    tags:
      - '*rdev'
      - 'rdev*'
    branches:
      - 'rdev-*'
      - '**/rdev-*'
      - '**-rdev'

env:
  DEPLOYMENT_STAGE: test
  # Force using BuildKit instead of normal Docker, required so that metadata
  # is written/read to allow us to use layers of previous builds as cache.
  DOCKER_BUILDKIT: 1
  COMPOSE_DOCKER_CLI_BUILD: 1
  DOCKER_REPO: ${{ secrets.ECR_REPO }}/

permissions:
  id-token: write
  contents: read

jobs:
  build-push-images:
    runs-on: ubuntu-20.04
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-region: us-west-2
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          role-duration-seconds: 900
      - name: Login to ECR
        uses: docker/login-action@v1
        with:
          registry: ${{ secrets.ECR_REPO }}
      - name: Login to ECR
        uses: docker/login-action@v1
        with:
          registry: ${{ secrets.CORE_PLATFORM_ECR_REPO }}
      - uses: actions/checkout@v2
      - name: Install happy
        uses: chanzuckerberg/github-actions/.github/actions/install-happy@install-happy-v1.4.2
        with:
          happy_version: "0.59.0"
      - name: Build component
        shell: bash
        run: |
          DOCKER_TAG=${GITHUB_REF#refs/heads/}
          DOCKER_TAG=${DOCKER_TAG#refs/tags/}
           # replace `/` with `_`
          DOCKER_TAG=${DOCKER_TAG//\//-}        
          happy push --aws-profile "" --tag sha-${GITHUB_SHA:0:8} --tag ${DOCKER_TAG}
