name: Docker Image Build

on:
  workflow_call:
    inputs:
      envs:
        description: 'Env names, comma delimited'
        required: true
        type: string
      path_filters:
        description: 'Glob patterns to match against changed files in the repository, comma delimited'
        required: true
        type: string
      branches:
        description: 'Branches to build on, comma delimited'
        required: false
        type: string
        default: '*'
      branches_ignore:
        description: 'Branches to skip build on, comma delimited'
        required: false
        type: string
        default: ''

jobs:
  get_commit_sha:
    runs-on: ubuntu-latest
    outputs:
      commit_sha: ${{ steps.get_sha.outputs.COMMIT_SHA }}
    steps:
      - uses: actions/checkout@v2
      - name: Get commit sha
        id: get_sha
        run: |
          echo "COMMIT_SHA=$(git rev-parse --verify HEAD)" >> $GITHUB_OUTPUT
  argus_builder:
    needs: get_commit_sha
    uses: chanzuckerberg/github-actions/.github/workflows/argus-docker-build.yaml@v2.11.1
    secrets: inherit
    with:
      branches: ${{ inputs.branches }}
      branches_ignore: ${{ inputs.branches_ignore }}
      path_filters: ${{ inputs.path_filters }}
      envs: ${{ inputs.envs }}
      images: |
        [
          {
            "name": "explorer",
            "context": ".",
            "dockerfile": "hosted/Dockerfile",
            "platform": "linux/amd64",
            "build_args": [
              "COMMIT_SHA=${{ needs.get_commit_sha.outputs.commit_sha }}"
            ]
          }
        ]
