name: Smoke Test

on:
  workflow_call:
    inputs:
      env:
        description: 'Env name'
        required: true
        type: string

jobs:
  smoke-test:
    # (thuang): We now run the smoke tests against 2 datasets sequentially, so need longer timeout
    timeout-minutes: 60
    runs-on: ubuntu-22.04
    defaults:
      run:
        working-directory: ./client
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version-file: "client/.nvmrc"
          cache: "npm"
          cache-dependency-path: "client/package-lock.json"
      - name: Install dependencies
        run: |
          npm ci
          npx playwright install --with-deps

      # Run e2e tests
      - name: Run e2e tests
        run: |
          npm run e2e-${{ inputs.env }}

      - name: Publish to Chromatic
        uses: chromaui/action@latest
        with:
          # ⚠️ Make sure to configure a `CHROMATIC_PROJECT_TOKEN` repository secret
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          workingDir: ./client
          # This is `npm run build-archive-storybook`
          buildScriptName: "build-archive-storybook"

      - name: Upload FE test results as an artifact
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: playwright-report
          path: ~/**/playwright-report/*
          retention-days: 14

      - name: Upload blob report to GitHub Actions Artifacts
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: all-blob-reports
          path: ~/**/blob-report/*
          retention-days: 1
